version: '3.8'

services:
    my-app-dockerfile:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APP_NAME=my-app-dockerfile
            - APP_PORT=8080
        ports:
            - "5051:8080"

    my-app-image:
        image: my-app
        environment:
            - APP_NAME=my-app-image
            - APP_PORT=8080
        ports:
            - "5052:8080"